# Generated by Django 3.2 on 2023-06-02 08:46

import ckeditor.fields
from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=services.uploader.Uploader.upload_image_of_logo)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('footer', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
