# Generated by Django 3.2 on 2023-05-15 07:41

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230509_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_image_to_product),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
