# Generated by Django 3.2 on 2023-05-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_aa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AA',
        ),
    ]
