# Generated by Django 3.2 on 2023-05-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
